version: "3.9"
services:
    nginx:
      build: services/nginx/
      container_name: nginx-container
      ports:
       - "8080:80"
      volumes:
         - ./app/:/var/www/html/
    php:
      build: services/php/
      expose:
       - 9000
      volumes:
        - ./app/:/var/www/html/
    db:
      image: mariadb
      ports:
        - "3266:3306"
      volumes:
        - mysql-data:/var/lib/mysql
      environment:
        MARIADB_ROOT_PASSWORD: password
        MARIADB_DATABASE: drupaldb
        MARIADB_PASSWORD: password
        MARIADB_USER: root
volumes:
  mysql-data:



